### ISSUE TITLE
Logout

### ISSUE THREAD

**Issue by michzimny** [up2university/single-sign-on#24]
Is there any way to log out from SSO, meaning to invalidate a user session?

If so, we could add the information to the docs.

CC @ebocchi

**Comment by foobarable** [comment]
https://wiki.shibboleth.net/confluence/display/CONCEPT/SLOIssues

**Comment by michzimny** [comment]
Ok, good point. 

I don't know yet what we want :)

**Comment by ebocchi** [comment]
Thanks for bringing this up.

It is not critical for the time being. I will redirect to [up2u homepage](https://www.up2university.eu) as logout action, even though no actual logout takes place. 
In future, it would be useful to have a, e.g, 'https://sso.up2university.eu/shibboleth/signout' to be called by every service behind SSO in order to log out users.

**Comment by foobarable** [comment]
The thing is, then we would need to send the logout to all other 
connected SPs of the session to log the user out in every other service 
as well. It's not as trivial as it seems. Please read the article ;)

**Comment by michzimny** [comment]
Currently, a user is able to log out from Moodle but is not able to log out from CERNBox.

@athird or @foobarable, could you tell us how the log-out is implemented in Moodle? Could we do it in the same way in CERNBox?

**Comment by foobarable** [comment]
Hi, we would need the owncloud session to reuse the shibboleth session. 
It's not that easy and we have not solved it for our owncloud yet either.

**Comment by michzimny** [comment]
I'm closing this as it seems it's not necessary on the SSO side.
